//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add Business Module" recipe.
//
//  
//
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace SmartHIS.HeThong.Constants
{
    /// <summary>
    /// Constants for workspace names.
    /// </summary>
    public class WorkspaceNames : SmartHIS.HeThong.Interface.Constants.WorkspaceNames
    {
    }
}
